import {
  LayoutDashboard,
  FileText,
  Handshake,
  Calendar,
  MessageSquareQuote,
  MessageSquare,
  Mail,
  BarChart3,
  Search,
  Settings,
  Layout,
  UserCog,
  Star,
  HandHelping,
  Image,
  Newspaper,
  Activity,
} from 'lucide-react';

export const RESOURCES = {
  articles: {
    label: 'Articles',
    icon: FileText,
    color: 'text-primary-500',
    bgColor: 'bg-primary-50',
    apiPath: '/articles',
    fields: ['title', 'category', 'status', 'author', 'views', 'updatedAt'],
  },
  partners: {
    label: 'Partners',
    icon: Handshake,
    color: 'text-purple-500',
    bgColor: 'bg-purple-50',
    apiPath: '/partners',
    fields: ['name', 'category', 'status', 'updatedAt'],
  },
  events: {
    label: 'Events',
    icon: Calendar,
    color: 'text-rose-500',
    bgColor: 'bg-rose-50',
    apiPath: '/events',
    fields: ['title', 'type', 'location', 'updatedAt'],
  },
  testimonials: {
    label: 'Testimonials',
    icon: MessageSquareQuote,
    color: 'text-amber-500',
    bgColor: 'bg-amber-50',
    apiPath: '/testimonials',
    fields: ['name', 'role', 'featured', 'updatedAt'],
  },
  newsletters: {
    label: 'Newsletter Subscribers',
    icon: Mail,
    color: 'text-emerald-500',
    bgColor: 'bg-emerald-50',
    apiPath: '/newsletter',
    fields: ['email', 'subscribed', 'updatedAt'],
  },
  contacts: {
    label: 'Contact Messages',
    icon: MessageSquare,
    color: 'text-gray-600',
    bgColor: 'bg-gray-100',
    apiPath: '/contact',
    fields: ['name', 'email', 'subject', 'read', 'createdAt'],
  },
  featureRequests: {
    label: 'Featured Requests',
    icon: Star,
    color: 'text-amber-500',
    bgColor: 'bg-amber-50',
    apiPath: '/feature-requests',
    fields: ['name', 'placeOfWork', 'typeOfWork', 'phoneNo', 'createdAt'],
  },
  joinInitiative: {
    label: 'Join Initiative',
    icon: HandHelping,
    color: 'text-emerald-500',
    bgColor: 'bg-emerald-50',
    apiPath: '/join-initiative',
    fields: ['name', 'phoneNo', 'city', 'state', 'createdAt'],
  },
  gallery: {
    label: 'Gallery Manager',
    icon: Image,
    color: 'text-violet-500',
    bgColor: 'bg-violet-50',
    apiPath: '/gallery',
    fields: [],
  },
  partnerApplications: {
    label: 'Partner Applications',
    icon: Handshake,
    color: 'text-primary-500',
    bgColor: 'bg-primary-50',
    apiPath: '/partner-applications',
    fields: ['name', 'organization', 'email', 'phoneNo', 'createdAt'],
  },
  mediaMentions: {
    label: 'Media Mentions',
    icon: Newspaper,
    color: 'text-blue-500',
    bgColor: 'bg-blue-50',
    apiPath: '/media-mentions',
    fields: ['title', 'source', 'date', 'url', 'updatedAt'],
  },
  researchReports: {
    label: 'Research & Reports',
    icon: FileText,
    color: 'text-purple-500',
    bgColor: 'bg-purple-50',
    apiPath: '/articles',
    fields: ['title', 'status', 'updatedAt'],
  },
  successStories: {
    label: 'Success Stories',
    singularLabel: 'Success Story',
    icon: FileText,
    color: 'text-emerald-500',
    bgColor: 'bg-emerald-50',
    apiPath: '/articles',
    fields: ['title', 'status', 'updatedAt'],
  },
  interviews: {
    label: 'Interviews',
    icon: FileText,
    color: 'text-amber-500',
    bgColor: 'bg-amber-50',
    apiPath: '/articles',
    fields: ['title', 'status', 'updatedAt'],
  },
};

export const NAV_ITEMS = [
  { label: 'Dashboard', icon: LayoutDashboard, path: '/', exact: true },
  {
    label: 'Manage Content',
    icon: FileText,
    path: '/content',
    children: Object.entries(RESOURCES).map(([key, res]) => ({
      label: res.label,
      icon: res.icon,
      path: `/content/${key}`,
    })),
  },
  { label: 'Analytics', icon: BarChart3, path: '/analytics' },
  { label: 'Traffic', icon: Activity, path: '/traffic' },
  { label: 'Homepage Builder', icon: Layout, path: '/homepage' },
  { label: 'SEO', icon: Search, path: '/seo' },
  { label: 'Users', icon: UserCog, path: '/users' },
  { label: 'Settings', icon: Settings, path: '/settings' },
];

export const ARTICLE_CATEGORIES = [
  'General',
  'Case Study',
  'Research',
  'Explainer',
  'Interview',
  'News',
  'Opinion',
  'Success Stories',
];

export const PARTNER_CATEGORIES = ['government', 'corporate', 'ngo', 'educational'];
export const EVENT_TYPES = ['upcoming', 'past'];

export const HOMEPAGE_SECTIONS = [
  { key: 'hero', label: 'Hero Banner' },
  { key: 'programs', label: 'What We Do' },
  { key: 'research', label: 'Success Stories' },
  { key: 'partners', label: 'Partners' },
  { key: 'mediaMentions', label: 'Media Mentions' },
  { key: 'testimonials', label: 'Testimonials' },
];
