#!/bin/bash
#
# RavivarVichar — Nginx SEO patch
#
# Run this ON THE DROPLET (one-time, idempotent):
#
#   bash scripts/apply-seo-nginx.sh
#
# It patches /etc/nginx/sites-available/ravivarvichar to:
#
#   1. Proxy /robots.txt and /sitemap.xml to the API server, which now
#      generates them dynamically (real sitemap + sitemap line).
#   2. Return a real 404 for unknown paths instead of the SPA shell.
#      Old-website URLs (/bank-sakhi, /Tags, /kahaniyan, ...) are not client
#      routes, so they now 404 — Google drops them from the index instead of
#      treating them as live pages.
#
# Safe: backs up the config first, aborts without touching anything if the
# expected patterns aren't found, and only reloads after `nginx -t` passes.
# Re-running it is a no-op.

set -euo pipefail

CONFIG="/etc/nginx/sites-available/ravivarvichar"

echo "[INFO] Patching $CONFIG"

if [ ! -f "$CONFIG" ]; then
  echo "[FAIL] $CONFIG not found. Is the site deployed with the documented nginx config?"
  exit 1
fi

BACKUP="${CONFIG}.bak-seo-$(date +%Y%m%d%H%M%S)"
cp "$CONFIG" "$BACKUP"
echo "[INFO] Backup saved: $BACKUP"

python3 <<'PY'
import re, sys

cfg_path = "/etc/nginx/sites-available/ravivarvichar"

with open(cfg_path) as f:
    cfg = f.read()

MARKER = "# ─── SEO (managed by"
if MARKER in cfg:
    print("[INFO] SEO blocks already present — nothing to do.")
    sys.exit(0)

# Reuse whatever the /api/ block proxies to (usually http://localhost:5000)
m = re.search(r"proxy_pass\s+([^;]+);", cfg)
if not m:
    print("[FAIL] No proxy_pass found in nginx config — aborting.")
    sys.exit(1)
proxy = m.group(1).strip()
print(f"[INFO] Proxying robots/sitemap to {proxy}")

seo_blocks = f"""    # ─── SEO (managed by scripts/apply-seo-nginx.sh — do not edit by hand) ───
    # Dynamic robots.txt + sitemap.xml generated by the API server
    location = /robots.txt {{
        proxy_pass {proxy};
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }}

    location = /sitemap.xml {{
        proxy_pass {proxy};
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }}
"""

old_api = "    location /api/ {"
if old_api not in cfg:
    print("[FAIL] 'location /api/ {' block not found — aborting. Nothing changed.")
    sys.exit(1)
cfg = cfg.replace(old_api, seo_blocks + old_api, 1)

old_spa = """    location / {
        try_files $uri $uri/ /index.html;
    }
"""
new_spa = """    # ─── SEO: known client routes get the SPA, unknown paths get a real 404 ───
    # (managed by scripts/apply-seo-nginx.sh — do not edit by hand)
    # Old-website URLs (/bank-sakhi, /Tags, /kahaniyan, ...) are NOT in this
    # list, so they now return 404 and Google drops them from the index.
    location = / {
        try_files /index.html =404;
    }

    location ~ ^/(about|articles|interviews|contact|media|get-featured|join-our-initiative|gallery|partner-with-us|what-we-do|recognitions|events|faq)(/|$) {
        try_files $uri $uri/ /index.html;
    }

    location / {
        try_files $uri $uri/ =404;
    }
"""
if old_spa not in cfg:
    print("[FAIL] SPA 'location / { try_files ... /index.html; }' block not found — aborting. Nothing changed.")
    sys.exit(1)
cfg = cfg.replace(old_spa, new_spa, 1)

with open(cfg_path, "w") as f:
    f.write(cfg)
print("[INFO] nginx config updated.")
PY

echo "[INFO] Testing nginx config..."
nginx -t

echo "[INFO] Reloading nginx..."
systemctl reload nginx

echo ""
echo "[PASS] Done. Verify from your local machine:"
echo "  curl -s https://ravivarvichar.in/robots.txt      # should end with the Sitemap line"
echo "  curl -s https://ravivarvichar.in/sitemap.xml     # real XML, not HTML"
echo "  curl -s -o /dev/null -w '%{http_code}\\n' https://ravivarvichar.in/bank-sakhi   # expect 404"
echo ""
echo "  Rollback if needed: cp ${CONFIG}.bak-seo-* ${CONFIG} && nginx -t && systemctl reload nginx"
